import Contact from "@/components/contact";
import Footer from "@/components/footer";
import Hero from "@/components/hero2";
import How from "@/components/how";
import OurStory from "@/components/ourstory";
import Prices from "@/components/prices";
import Sentence from "@/components/sentence";
import { SEO } from "@/components/seo";
import Services from "@/components/services2";
import { Inter } from "@next/font/google";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>AeFFe Consulenze</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <SEO />
      </Head>
      <main>
        <Hero />
        <Sentence />
        <Services />
        <OurStory />
        <How />
        <Prices />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
